---
deployment:
  tasks:
    - export DEPLOYPATH=/home/edvokttv/edvora-project/
    - rsync -av --exclude='.env' --exclude='storage/' --exclude='bootstrap/cache/' --exclude='.git/' --exclude='node_modules/' ./ $DEPLOYPATH
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;