---
deployment:
  tasks:
    - export DEPLOYPATH=/home/edvokttv/edvora-project/
    - /usr/bin/rsync -av --exclude='.env' --exclude='storage/' --exclude='bootstrap/cache/' --exclude='.git/' --exclude='node_modules/' --exclude='public/index.php' --exclude='public/.htaccess' --exclude='public/robots.txt' --exclude='public/favicon.ico' --exclude='public/app.token' ./ $DEPLOYPATH
    - /usr/bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /usr/bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;