---
deployment:
  tasks:
    - export DEPLOYPATH=/home/edvokttv/edvora-project/
    - export PUBLICPATH=/home/edvokttv/public_html/
    - /usr/bin/rsync -av --exclude='.env' --exclude='storage/' --exclude='bootstrap/cache/' --exclude='.git/' --exclude='node_modules/' --exclude='public/index.php' --exclude='public/.htaccess' --exclude='public/robots.txt' --exclude='public/favicon.ico' --exclude='public/app.token' ./ $DEPLOYPATH
    - /usr/bin/rsync -av --exclude='.htaccess' --exclude='index.php' --exclude='robots.txt' --exclude='favicon.ico' --exclude='storage' ./public/ $PUBLICPATH
    - /usr/bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /usr/bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /usr/bin/find $PUBLICPATH -type d -exec chmod 755 {} \;
    - /usr/bin/find $PUBLICPATH -type f -exec chmod 644 {} \;
    - /usr/local/bin/php $DEPLOYPATH/artisan view:clear || true
    - /usr/local/bin/php $DEPLOYPATH/artisan route:clear || true
    - /usr/local/bin/php $DEPLOYPATH/artisan cache:clear || true